# Generated by Django 4.2.1 on 2023-07-23 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_attempt',
            new_name='StudentAttempt',
        ),
    ]
