# Generated by Django 4.2.1 on 2023-07-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_student_attempt_studentattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
