# Generated by Django 4.2.1 on 2023-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
