# Generated by Django 4.2.1 on 2023-06-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afaq', '0002_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='notfication',
        ),
    ]
