# Generated by Django 4.2.1 on 2023-06-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afaq', '0005_lecture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='videourl',
            field=models.URLField(blank=True),
        ),
    ]
