# Generated by Django 4.2.1 on 2023-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afaq', '0007_alter_lecture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_month',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], null=True),
        ),
    ]
