# Generated by Django 4.2.1 on 2023-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afaq', '0008_lecture_lecture_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_month',
            field=models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], max_length=20, null=True),
        ),
    ]
