# Generated by Django 4.2.1 on 2023-06-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afaq', '0011_questions_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='img',
        ),
        migrations.AddField(
            model_name='questions',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afaq.lecture'),
        ),
    ]
