# Generated by Django 4.2.1 on 2023-07-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_student_attempt_studentattempt'),
        ('afaq', '0012_remove_questions_img_questions_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.quiz'),
        ),
    ]
